config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', :registrations => "users/registrations"
  }

  resources :expenses
  resources :incomes
  resources :expenses

  resources :users do
    resources :incomes
    resources :expenses
  end
  get 'welcome/index'

  # You can have the root of your site routed with "root"
  root 'welcome#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :expenses, dependent: :destroy
  has_many :incomes, dependent: :destroy

  validates_presence_of :Name
  validates_presence_of :Age

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
before_action :configure_sign_up_params, only: [:create]
before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit( :email, :password, :password_confirmation, :Name, :Age)
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit( :email, :password, :password_confirmation, :Name, :Age)
    end
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:Name, :Age, :password_confirmation, :current_password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :Age %><br>
    <%= f.number_field :Age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6">
      <h1>Editing User</h1>

      <%= render 'form' %>

      <%= link_to 'Back', users_path %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <p id="notice"><%= notice %></p>

          <h1>Users List</h1>

          <table class = "table table-hover  table-condensed">
            <thead>
              <tr>
                <th>Name</th>
                <th>Age</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= user.Name %></td>
                  <td><%= user.Age %></td>
                  <td><%= link_to 'Show Budget', user, :class=> "btn btn-default btn-xs" %></td>
                  <td><%= link_to 'Edit User', edit_user_path(user), :class=> "btn btn-info btn-xs" %></td>
                  <td><%= link_to 'Delete User', user, method: :delete, data: { confirm: 'Are you sure?' }, :style=>"color:#fff;", :class=> "btn btn-danger btn-xs"%></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <br>

          <%= link_to 'New User', new_user_path, class: "btn btn-warning" %>
    </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6">
      <h1>New Users</h1>

      <%= render 'form' %>

      <%= link_to 'Back', users_path %>
  </div>
</div>

app/views/users/show.html.erb
<!-- variables -->
<% totalIncome = 0 %>
<% totalExpense = 0 %>
<% netIncome = 0 %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <h2>Welcome back <%= @user.Name %></h2>
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Age:</strong>
        <%= @user.Age %>
      </p>

      <%= link_to 'Edit', edit_user_path(@user) %> |
      <%= link_to 'Back', users_path %>
  </div>
</div>

<div class="row">
  <h2>Incomes</h2>
  <div class="col-md-6">
    <div class="well">
      <div id="incomes">

        <table class = "table table-condensed">
          <thead>
          <tr>
            <th>Income Source</th>
            <th>Amount</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>

          <% @user.incomes.each do |income| %>
              <tr>
                <td><%= h(income.income_source) %></td>
                <td><%= h(income.amount)%></td>
                <td><%= link_to 'Edit', edit_income_path(income) %></td>
                <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% totalIncome += income.amount %>
          <% end %>
          </tbody>
        </table>
        Your total Income is $<%= totalIncome %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
      <%= form_for([@users, Income.new]) do |f| %>
          <div class="field">
            <%= f.label :user_id %><br>
            <%= f.text_field :user_id, :readonly => true, :value => @user.id%>
          </div>
          <div class="field">
            <%= f.label :income_source %><br>
            <%= f.text_field :income_source %>
          </div>
          <div class="field">
            <%= f.label :amount %><br>
            <%= f.text_field :amount %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
      <% end %>
  </div>
</div>

<div class="row">
  <h2>Expenses</h2>
  <div class="col-md-6">
    <div class="well">
      <div id="incomes">

        <table class = "table table-condensed">
          <thead>
          <tr>
            <th>Expense Source</th>
            <th>Expense Type</th>
            <th>Amount</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% @user.expenses.each do |expense| %>
              <tr>
                <td><%= h(expense.expense_source) %></td>
                <td><%= h(expense.expense_type) %></td>
                <td><%= h(expense.amount)%></td>
                <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
                <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% totalExpense += expense.amount %>
          <% end %>
          <% netIncome += totalIncome - totalExpense %>
          </tbody>
        </table>
        Your total Expense is $<%= totalExpense %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <%= form_for([@users, Expense.new]) do |f| %>
        <div class="field">
          <%= f.label :user_id %><br>
          <%= f.text_field :user_id, :readonly => true, :value => @user.id%>
        </div>
        <div class="field">
          <%= f.label :expense_source %><br>
          <%= f.text_field :expense_source %>
        </div>
        <div class="field">
          <%= f.label :expense_type %><br>
          <%= f.text_field :expense_type %>
        </div>
        <div class="field">
          <%= f.label :amount %><br>
          <%= f.text_field :amount %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
    <% end %>
  </div>
</div>


<div class="row">
  <h2>Net Income</h2>
  <div class="col-md-6">
    <div class="well">
      Your net income is $<%= netIncome %>
    </div>
  </div>
  <div class="col-md-6">

  </div>
</div>