config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', :registrations => "users/registrations"
  }

  resources :expenses
  resources :incomes
  resources :expenses

  resources :users do
    resources :incomes
    resources :expenses
  end
  get 'welcome/index'

  # You can have the root of your site routed with "root"
  root 'welcome#index'
end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :user_id
  validates_presence_of :income_source
  validates_presence_of :amount
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to (:back), notice: "Income has been saved successfully." }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { redirect_to (:back), error: "Income could not be saved."}
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to (:back), notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to (:back), notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:user_id, :income_source, :amount)
    end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.erb
<%= form_for(@income) do |f| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% @income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :income_source %><br>
    <%= f.text_field :income_source %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
        <h1>Editing Income</h1>

        <%= render 'form' %>

        <%= link_to 'Back', incomes_path %>
    </div>
  </div>
</div>

app/views/incomes/index.html.erb
<body>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p id="notice"><%= notice %></p>

          <h1>Listing Incomes</h1>

          <table class = "table table-hover  table-condensed">
            <thead>
            <tr>
              <th>User</th>
              <th>Income source</th>
              <th>Amount</th>
              <th colspan="3"></th>
            </tr>
            </thead>

            <tbody>
            <% @incomes.each do |income| %>
                <tr>
                  <td><%= income.user_id %></td>
                  <td><%= income.income_source %></td>
                  <td><%= income.amount %></td>
                  <td><%= link_to 'Edit Details', edit_income_path(income), :class=> "btn btn-info btn-xs" %></td>
                  <td><%= link_to 'Remove Income', income, method: :delete, data: { confirm: 'Are you sure?' }, :style=>"color:#fff;", :class=> "btn btn-danger btn-xs" %></td>
                </tr>
            <% end %>
            </tbody>
          </table>

          <br>

          <%= link_to 'Go to Users', users_path %>
        </div>
      </div>
    </div>
</body>

app/views/incomes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
        <h1>New Income</h1>

        <%= render 'form' %>

        <%= link_to 'Back', incomes_path %>
    </div>
  </div>
</div>

app/views/incomes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>User:</strong>
          <%= @income.user_id %>
        </p>

        <p>
          <strong>Income source:</strong>
          <%= @income.income_source %>
        </p>

        <p>
          <strong>Amount:</strong>
          <%= @income.amount %>
        </p>

        <%= link_to 'Edit', edit_income_path(@income) %> |
        <%= link_to 'Back', incomes_path %>
    </div>
  </div>
</div>