config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', :registrations => "users/registrations"
  }

  resources :expenses
  resources :incomes
  resources :expenses

  resources :users do
    resources :incomes
    resources :expenses
  end
  get 'welcome/index'

  # You can have the root of your site routed with "root"
  root 'welcome#index'
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to (:back), notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to (:back), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to (:back), notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:user_id, :expense_source, :expense_type, :amount)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id, :readonly => true%>
  </div>
  <div class="field">
    <%= f.label :expense_source %><br>
    <%= f.text_field :expense_source %>
  </div>
  <div class="field">
    <%= f.label :expense_type %><br>
    <%= f.text_field :expense_type %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<div class="row">
  <div class="col-md-12">
      <h1>Editing Expense</h1>

      <%= render 'form' %>
      <%= link_to 'Back', expenses_path %>
  </div>
</div>

app/views/expenses/index.html.erb
<div class="row">
  <div class="col-md-12">
    <p id="notice"><%= notice %></p>

    <h1 class = "padding">Listing Expenses</h1>

    <table class="table table-hover  table-condensed">
      <thead>
      <tr>
        <th>User</th>
        <th>Expense source</th>
        <th>Expense type</th>
        <th>Amount</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @expenses.each do |expense| %>
        <tr>
          <td><%= expense.user_id %></td>
          <td><%= expense.expense_source %></td>
          <td><%= expense.expense_type %></td>
          <td><%= expense.amount %></td>
          <td><%= link_to 'Edit Details', edit_expense_path(expense), :class=> "btn btn-info btn-xs" %></td>
          <td><%= link_to 'Remove Expense', expense, method: :delete, data: { confirm: 'Are you sure?' }, :style=>"color:#fff;", :class=> "btn btn-danger btn-xs" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Go to Users', users_path %>
  </div>
</div>

app/views/expenses/new.html.erb
<div class="row">
  <div class="col-md-12">
      <h1>New Expense</h1>

      <%= render 'form' %>

      <%= link_to 'Back', expenses_path %>
  </div>
</div>

app/views/expenses/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>User:</strong>
          <%= @expense.user_id %>
        </p>

        <p>
          <strong>Expense source:</strong>
          <%= @expense.expense_source %>
        </p>

        <p>
          <strong>Expense type:</strong>
          <%= @expense.expense_type %>
        </p>

        <p>
          <strong>Amount:</strong>
          <%= @expense.amount %>
        </p>

        <%= link_to 'Edit', edit_expense_path(@expense) %> |
        <%= link_to 'Back', expenses_path %>
    </div>
  </div>
</div>